anime_list = [
    {"title": "Naruto", "genre": "Action", "vibe": "Exciting", "rating": "PG-13", "Description": "A young ninja strives to become the strongest ninja and Leader of his village."},
    {"title": "Your lie in april", "genre": "Romance", "vibe": "Emotional", "Description": "A piano prodigy who loses his ability to hear the piano after his mother's death meets a spirited violinist."},
    {"title": "Attack on Titan", "genre": "Action", "vibe": "Dark", "Description": "In a world where humanity is on the brink of extinction due to giant humanoid Titans, a group of soldiers fights for survival."},
    {"title": "Death Note", "genre": "Mystery", "vibe": "Dark", "Description": "A high school student discovers a supernatural notebook that allows him to kill anyone by writing their name in it."},
    {"title": "Kaguya-sama: Love is War", "genre": "Romance", "vibe": "Funny", "Description": "Two high school students in student council try to get the other to confess their love first."},
    {"title": "Fullmetal Alchemist: Brotherhood", "genre": "Adventure", "vibe": "Exciting", "Description": "Two brothers use alchemy in their quest to find the Philosopher's Stone to restore their bodies after a failed alchemical experiment."},
    {"title": "Demon Slayer", "genre": "Action", "vibe": "Emotional", "Description": "A young boy becomes a demon slayer to avenge his family and cure his sister who has turned into a demon."},
    {"title": "Myhero Academia", "genre": "Action", "vibe": "Exciting", "Description": "In a world where people with superpowers (Quirks) are common, A boy without powers dreams of becoming a hero"},
    {"title": "Haikyuu!!", "genre": "Sports", "vibe": "Exciting", "Description": "A high school volleyball team strives to become the best in Japan."},
    {"title": "Clannad", "genre": "Romance", "vibe": "Emotional", "Description": "A high school student who is in love with a girl who has a mysterious past."},
    {"title": "Black Clover", "genre": "Adventure", "vibe": "Exciting", "Description": "A young boy born without magic in a world where magic is everything strives to become the Wizard King."},
    {"title": "Spy x Family", "genre": "Comedy", "vibe": "Funny", "Description": "A spy who must build a fake family for a mission ends up adopting a telepathic girl and marrying an assassin."},
    {"title": "Bleach", "genre": "Action", "vibe": "Exciting", "Description": "A teenager with the ability to see ghosts becomes a Soul Reaper, protecting the living world from evil spirits."},
    {"title": "One Piece", "genre": "Adventure", "vibe": "Exciting", "Description": "A group of pirates search for the ultimate treasure, the One Piece, to become the Pirate King"},
    {"title": "Tokyo Ghoul", "genre": "Horror", "vibe": "Dark", "Description": "A college student becomes a half-ghoul after a deadly encounter and must navigate the dangerous world of ghouls."},
    {"title": "Jujutsu Kaisen", "genre": "Action", "vibe": "Exciting", "Description": "A high school student joins a secret organization to fight cursed spirits after ingesting a powerful cursed object."},
    {"title": "Hunter x Hunter", "genre": "Adventure", "vibe": "Exciting", "Description": "A young boy embarks on a journey to become a Hunter and find his father."},
    {"title": "Kimi no Na wa", "genre": "Romance", "vibe": "Emotional", "Description": "Two teenagers mysteriously swap bodies and must navigate each other's lives while trying to meet in person."},
    {"title": "Kaiju No. 8", "genre": "Sci-Fi", "vibe": "Exciting", "Description": "In a world plagued by giant monsters, a man gains the ability to transform into a kaiju and joins the defense force."},
    {"title": "Fire Force", "genre": "Action", "vibe": "Exciting", "Description": "A special fire brigade fights against spontaneous human combustions that turn people into living infernos."},
    {"title": "Kamisama Kiss", "genre": "Romance", "vibe": "Funny", "Description": "A high school student who is in love with a girl who has a mysterious past."},
]